/**
 * Utility functions for exporting tabular clinical data to CSV/Excel and triggering printing.
 */

export function exportToCSV(filename, data) {
  if (!data || !data.length) {
    alert("No data available to export.");
    return;
  }

  const headers = Object.keys(data[0]);
  const csvRows = [];

  // Header row
  csvRows.push(headers.map((h) => `"${h.replace(/"/g, '""')}"`).join(","));

  // Data rows
  for (const row of data) {
    const values = headers.map((header) => {
      const val = row[header] === null || row[header] === undefined ? "" : String(row[header]);
      return `"${val.replace(/"/g, '""')}"`;
    });
    csvRows.push(values.join(","));
  }

  // Prepend UTF-8 BOM so Microsoft Excel renders characters and accents properly
  const csvString = "\uFEFF" + csvRows.join("\r\n");
  const blob = new Blob([csvString], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${new Date().toISOString().split("T")[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generates an elegant print-ready clinical report that triggers the browser's
 * native print / "Save as PDF" dialog.
 */
export function printReport({ title, subtitle, columns, rows }) {
  if (!rows || !rows.length) {
    alert("No records to print.");
    return;
  }

  const printWindow = window.open("", "_blank", "width=960,height=700");
  if (!printWindow) {
    window.print();
    return;
  }

  const dateStr = new Date().toLocaleString();
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>${title} - Mini-OPD</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            margin: 28px;
            color: #1e293b;
            background: #fff;
          }
          .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 14px;
            margin-bottom: 20px;
          }
          .brand-title {
            font-size: 22px;
            font-weight: 800;
            color: #1e40af;
            margin: 0;
            display: flex;
            align-items: center;
            gap: 8px;
          }
          .doc-subtitle {
            font-size: 14px;
            color: #475569;
            margin-top: 4px;
            font-weight: 500;
          }
          .meta-box {
            text-align: right;
            font-size: 12px;
            color: #64748b;
            line-height: 1.5;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 12px;
          }
          th {
            background: #f1f5f9;
            color: #334155;
            font-weight: 700;
            text-align: left;
            padding: 8px 10px;
            border: 1px solid #cbd5e1;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          td {
            padding: 8px 10px;
            border: 1px solid #e2e8f0;
            color: #334155;
          }
          tr:nth-child(even) {
            background: #f8fafc;
          }
          .footer {
            margin-top: 28px;
            border-top: 1px solid #e2e8f0;
            padding-top: 12px;
            font-size: 11px;
            color: #94a3b8;
            display: flex;
            justify-content: space-between;
          }
          @media print {
            body { margin: 12mm; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="brand-title">🏥 Mini-OPD Healthcare Management</h1>
            <div class="doc-subtitle">${title} ${subtitle ? `— ${subtitle}` : ""}</div>
          </div>
          <div class="meta-box">
            <div><strong>Generated:</strong> ${dateStr}</div>
            <div><strong>Total Records:</strong> ${rows.length}</div>
            <div><strong>Generated By:</strong> Administrator</div>
          </div>
        </div>
        <table>
          <thead>
            <tr>
              ${columns.map((c) => `<th>${c}</th>`).join("")}
            </tr>
          </thead>
          <tbody>
            ${rows
              .map(
                (r) =>
                  `<tr>${r.map((v) => `<td>${v !== undefined && v !== null ? v : "—"}</td>`).join("")}</tr>`
              )
              .join("")}
          </tbody>
        </table>
        <div class="footer">
          <span>Mini-OPD Automated Clinical System &bull; Confidential Administrative Report</span>
          <span>Page 1 of 1</span>
        </div>
        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 300);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}
